version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: jak-db
    environment:
      POSTGRES_DB: exam_db
      POSTGRES_USER: jak_admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jak_admin -d exam_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile_Jak
    container_name: jak-app-instance
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exam_db
      - SPRING_DATASOURCE_USERNAME=jak_admin
      - SPRING_DATASOURCE_PASSWORD=password123
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
